### ISSUE TITLE
猜版成功页UI问题

### ISSUE THREAD

**Issue by Jasonzhu1207** [klxiaoniu/QQVersionList#27]
**描述错误**
猜版成功页面按钮重叠

**重现步骤**
重现行为的步骤：
1. 转到“猜版”
2. 点击“开始”
3. 成功后一个按钮与复制按钮重叠

**截图**
![Screenshot_20240329_084812_com.xiaoniu.qqversionlist.jpg](https://github.com/klxiaoniu/QQVersionList/assets/159670257/5dd3cc79-6573-4a22-955b-cc8cee607cb3)

**智能手机（请填写以下信息）：**
 - 设备：HUAWEI Mate 30
 - 操作系统：Android 12

**Comment by ArcticFoxPro** [comment]
感谢您给 QQ Ver. Tool 提出了 Issue。

我们先前已经通过其他渠道得知了此问题，正在想办法进行优化。目前拟定的方案是 左侧 4 按钮套一个横向滚动组件 或 取消右侧复制按钮的文字，具体还需要一些时间决策，感谢您的耐心等待。

**Comment by klxiaoniu** [comment]
https://github.com/klxiaoniu/QQVersionList/actions/runs/8478435751

**Comment by ArcticFoxPro** [comment]
> https://github.com/klxiaoniu/QQVersionList/actions/runs/8478435751

可以在这个包里验证下是否修复了哦，给左侧 4 按钮添加了横向滚动组件。
