### ISSUE TITLE
猜版报错

### ISSUE THREAD

**Issue by Jasonzhu1207** [klxiaoniu/QQVersionList#28]
**描述错误**
猜版是出现报错
javax.net.ssl.SSLHandshakeException: connection closed

**重现步骤**
重现行为的步骤：
1. 转到“猜版”
2. 填入“9.0.35-测试-15995”
3. 进行一段时间后出现“javax.net.ssl.SSLHandshakeException: connection closed”

**截图**
![Screenshot_20240329_201401_com.xiaoniu.qqversionlist.jpg](https://github.com/klxiaoniu/QQVersionList/assets/159670257/d22941c4-0d63-404c-a129-7f50734e8a6e)

**智能手机（请填写以下信息）：**
 - 设备：HUAWEI Mate 30
 - 操作系统：Android 12

**Comment by klxiaoniu** [comment]
过程中放到后台了吗？

**Comment by Jasonzhu1207** [comment]
> 过程中放到后台了吗？

屏幕常亮，连小窗都没开

**Comment by klxiaoniu** [comment]
重试吧，网络问题

**Comment by Jasonzhu1207** [comment]
> 重试吧，网络问题

好滴，谢牛
