### ISSUE TITLE
一些QQ版本下载链接格式不属于任何一个猜版格式

### ISSUE THREAD

**Issue by saddestboy** [klxiaoniu/QQVersionList#60]
官网下8.9.28版本的下载链接为<https://downv6.qq.com/qqweb/QQ_1/android_apk/Android_8.9.28.10155_537147618_64.apk>，四个猜测版本的链接格式该链接均不符合。

**Comment by saddestboy** [comment]
怀疑是QQ在9.0之后修改了版本号对应链接的规则

**Comment by ArcticFoxPro** [comment]
这个格式是在小版本号后面加了 appid，已在 QQNT 8.9.58 测试版废弃。

**Comment by ArcticFoxPro** [comment]
你好，我先为您关闭这个 issue 了。
后续您可以随时重新打开此 issue，如有其他问题可以提出新的 issue(s)。
