### ISSUE TITLE
8.9.58测试版无法猜到

### ISSUE THREAD

**Issue by pphh2606** [klxiaoniu/QQVersionList#76]
https://downv6.qq.com/qqweb/QQ_1/android_apk/qq_8.9.58.11045_64.apk
![Screenshot_2024-09-16-11-00-52-629_tw nekomimi nekogram](https://github.com/user-attachments/assets/6a5ab71a-65c6-4de0-b4de-f71164e06870)

**Comment by ArcticFoxPro** [comment]
我看了下，`https://downv6.qq.com/qqweb/QQ_1/android_apk/qq_<主版本号>.<小版本号>_64.apk` 这种格式似乎是仅在 8.9.58 测试版出现过，在 8.9.58 测试版前后，包括 8.9.58 正式版都不是这种格式。

**Comment by ArcticFoxPro** [comment]
您好，请尝试 https://github.com/klxiaoniu/QQVersionList/releases/tag/v1.3.9 。此版本在设置中新增了对 `https://downv6.qq.com/qqweb/QQ_1/android_apk/qq_<主版本号>.<小版本号>_64.apk` 格式的支持。
